# This workflow updates Git submodules daily
name: Daily Git Submodule Update

on:
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
        continue-on-error: false  # Fails if the checkout step has an issue

      - name: Update Git Submodules
        run: |
          echo "Starting submodule sync --recursive..."
          git submodule sync --recursive || { echo "Submodule sync failed"; exit 1; }
          echo "Starting update --init --recursive ..."
          git submodule update --init --recursive || { echo "Submodule initialization failed"; exit 1; }
          echo "Starting submodule update --remote --merge ..."
          git submodule update --remote --merge || { echo "Submodule update failed"; exit 1; }
        shell: bash
        
      - name: Download Moodle version file
        run: |
          wget -q https://raw.githubusercontent.com/moodle/moodle/MOODLE_403_STABLE/version.php -O version.php
          if [ ! -s version.php ]; then
            echo "Failed to download Moodle version file"
            exit 1
          fi
        shell: bash
              
      - name: Push updated submodules
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Automated submodule update"
          git push
        shell: bash

